# Generated by Django 4.2 on 2023-04-24 07:37

import authdjango.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, upload_to='files', validators=[authdjango.validators.FileValidator]),
        ),
    ]
