# Generated by Django 4.2 on 2023-04-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
    ]
