# Generated by Django 4.2 on 2023-04-24 08:00

import authdjango.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, upload_to='files', validators=[authdjango.validators.FileValidator]),
        ),
    ]
