# Generated by Django 4.2 on 2023-04-28 15:56

import authdjango.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, validators=[authdjango.validators.TextValidator(regex='')], verbose_name='Наименование'),
        ),
    ]
