# Generated by Django 4.2 on 2023-05-16 11:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_file_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
