# Generated by Django 4.2 on 2023-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_username_user_phone_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='email является логином пользователя', max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
